image:
  tag: 8.4.3

architecture: replication

auth:
  rootPassword: root@mysql
  createDatabase: true
  database: "csv"
  username: "admin"
  password: "csv@password"

replication:
  enabled: true
  user: replicator          # Replication user
  password: MySQLreplicator  # Replication password
  mode: asynchronous

service:
  type: ClusterIP
  port: 3306 

primary:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3306"
  labels:
    app: mysql
    role: primary
  persistence:
    enabled: true
    existingClaim: "mysql-pvc"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                  - ap-south-1a

volumePermissions:
  enabled: true

initdbScripts:
  noop.sql: ""

secondary:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3306"
  labels:
    app: mysql
    role: secondary
  replicaCount: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                  - ap-south-1b
  persistence:
    enabled: true
    existingClaim: "mysql-pvc-slave"
