apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ebs-sc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-slave
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ebs-sc
