apiVersion: v1
kind: Service
metadata:
  name: todo-app
  labels:
    app: fastapi
spec:
  type: LoadBalancer
  selector:
    app: perx
  ports:
    - protocol: TCP
      port: 80                
      targetPort: 8000
