image:
  tag: 8.4.4

architecture: replication

auth:
  rootPassword: "root@mysql"
  createDatabase: true
  database: "todo"
  username: "admin"
  password: "todo@password"
  host: "%"

replication:
  enabled: true
  user: replicator          # Replication user
  password: MySQLreplicator  # Replication password
  mode: asynchronous

service:
  type: ClusterIP
  port: 3306 

primary:
  startupProbe:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 15
    successThreshold: 1
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3306"
  labels:
    app: mysql
    role: primary
  persistence:
    enabled: true
    storageClass: standard
    size: 8Gi

volumePermissions:
  enabled: true

initdbScripts:
  create_table.sql: |
    CREATE DATABASE IF NOT EXISTS todo;
    USE todo;

    CREATE TABLE IF NOT EXISTS todos (
      task VARCHAR(255)
      );

secondary:
  startupProbe:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 15
    successThreshold: 1
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3306"
  labels:
    app: mysql
    role: secondary
  replicaCount: 1
  persistence:
    enabled: true
    size: 8Gi
    storageClass: standard
