apiVersion: v1
kind: Service
metadata:
  name: app-service-lb
  namespace: default
  labels:
    app: app-service
spec:
  type: LoadBalancer
  selector:
    app: perx
  ports:
    - protocol: TCP
      port: 80           
      targetPort: 8080
